# Generated by Django 5.0.3 on 2024-03-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_id',
            field=models.CharField(blank=True, editable=False, max_length=22, unique=True),
        ),
    ]
